name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v4
    - name: Build wiremock image
      run: |
        docker build ./wiremock --tag docker.io/kostakoff/containerized-tools:wiremock3.5.2
    - name: Push wiremock image
      run: |
        docker push docker.io/kostakoff/containerized-tools:wiremock3.5.2
    - name: Build ssh-server image
      run: |
        docker build ./ssh-server --tag docker.io/kostakoff/containerized-tools:ssh-server
    - name: Push ssh-server image
      run: |
        docker push docker.io/kostakoff/containerized-tools:ssh-server
    - name: Build newman image
      run: |
        docker build ./newman --tag docker.io/kostakoff/containerized-tools:newman
    - name: Push newman image
      run: |
        docker push docker.io/kostakoff/containerized-tools:newman
    - name: Build support-tools image
      run: |
        docker build ./support-tools --tag docker.io/kostakoff/containerized-tools:support-tools
    - name: Push support-tools image
      run: |
        docker push docker.io/kostakoff/containerized-tools:support-tools
